### ISSUE TITLE
UnboundLocalError possible in MagneticFieldCalculator.calculate()

### ISSUE THREAD

**Issue by Liam-Deacon** [filips123/MagneticFieldCalculator#1]
Not sure why yet - the issue was flagged by my CI pipeline after the new year (1st Jan 2020), so may be related to API changes?
```
        request = {
            'latitude': latitude,
            'longitude': longitude,
    
            'altitude': altitude,
            'depth': depth,
            'radius': radius,
    
            'year': year,
            'date': date,
    
            'format': 'json',
        }
    
        parameters = urllib.parse.urlencode({k: v for k, v in request.items() if v is not None})
    
        for base_url in self.custom_url, self.main_url:
            if base_url:
                try:
                    url = base_url \
                    + '/' + self.model \
                    + '/' + self.revision \
                    + ('v' + self.sub_revision if self.sub_revision else '') \
                    + '?' + parameters
    
                    request = urllib.request.Request(url)
    
                    if username and password:
                        auth = base64.b64encode(b'%s:%s' % (username, password))
                        request.add_header("Authorization", "Basic %s" % auth)
    
                    response = urllib.request.urlopen(url).read()
                    result = json.loads(response.decode('utf-8'))
    
                    break
    
                except (URLError, ValueError) as err:
                    error = err
    
        try:
>           return result['geomagnetic-field-model-result']
E           UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by filips123** [comment]
Geomagnetic Model Web Service now only supports World Magnetic Model 2020, which only supports from 2020 to 2030. You are probably trying to use old unsupported model version or date that is not supported by model you are trying to use.

---

You can currently use on the the following models:

> The World Magnetic Model (WMM) revision 2020 is available through this web service. To use this model, set the 'model' parameter to 'WMM' and the 'revision' parameter to '2020'. Valid dates for this model are from 2020 to 2030, though reduced accuracy should be expected for dates beyond 2025

> The International Geomagnetic Reference Field (IGRF) revision 13 is available through this web service. To use this model, set the 'model' parameter to 'IGRF' and the 'revision' parameter to '13'.

> The BGS Global Geomagnetic Model (BGGM) revisions 1994 to 2019 are available through this web service. To use this model, set the 'model' parameter to 'BGGM' and the 'revision' parameter to a value between '1994' and '2019'.

> The BGS Global Geomagnetic Model (BGGM) error model revision 2019 is available through this web service. To use this model, set the 'model' parameter to 'BGGMERR' and the 'revision' parameter to '2019'.

> For any model the 'revision' can be set to 'current' to use the most recent revision.

**Comment by filips123** [comment]
I updated examples to use new valid dates. They are now released in the latest version.

However, unfortunately, I can't fix problems with invalid dates for models itself, as they depend on data provided by BGS. If you want to use other dates, you have to use other models.

I think that some more informative error would be nice, however, the API just provides few generic HTML error pages so the program can't detect what exactly went wrong.
